### ISSUE TITLE
game crashes the Game Loader when uploading

### ISSUE THREAD

**Issue by 0x1f415** [TEAMarg/ID-48-Fantasy-Rampage#1]
hey, I just got my arduboy today and I've been having fun playing around with it.

when I tried to upload this game using the windows version of the game loader, the loader crashes. I'm not sure that the problem is in the loader because it loads other games fine, and regardless I couldn't find a bug tracker for the loader.

I checked the logs folder, but unfortunately the program did not write any logs before it crashed.

**Comment by 0x1f415** [comment]
uploading the hex worked fine.

**Comment by JO3RI** [comment]
I found out what is wrong. in the json file, we are still referring at v10 instead of v101. Going to make a new version v102, to fix this. I'll let you know when it's done

**Comment by JO3RI** [comment]
Voila @0x1f415 should be fixed now in [version v1.0.2](https://github.com/TEAMarg/ID-48-Fantasy-Rampage/releases/tag/v1.0.2). Thanks for letting us know, please try again an let us know. 

Enjoy the game.
